env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*  
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy
brews:
  - tap:
      owner: hupe1980
      name: homebrew-scan4log4shell
    homepage:  https://github.com/hupe1980/scan4log4shell
    description: Scanner to detect vulnerable log4j versions on your file-system or to send specially crafted requests and catch callbacks of systems that are impacted by log4j log4shell vulnerability
    license: MIT
    test: |
      system "#{bin}/scan4log4shell -v"
    install: |-
      bin.install "scan4log4shell"
      bash_completion.install "completions/scan4log4shell.bash" => "scan4log4shell"
      zsh_completion.install "completions/scan4log4shell.zsh" => "_scan4log4shell"
      fish_completion.install "completions/scan4log4shell.fish"
scoop:
  bucket:
    owner: hupe1980
    name: scan4log4shell-bucket
  homepage:  https://github.com/hupe1980/scan4log4shell
  description: Scanner to detect vulnerable log4j versions on your file-system or to send specially crafted requests and catch callbacks of systems that are impacted by log4j log4shell vulnerability
  license: MIT
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/hupe1980/scan4log4shell
    maintainer: Frank Hübner <frankhuebner1980@gmail.com>
    description: Scanner to detect vulnerable log4j versions on your file-system or to send specially crafted requests and catch callbacks of systems that are impacted by log4j log4shell vulnerability
    license: MIT
    contents:
      - src: ./completions/scan4log4shell.bash
        dst: /etc/bash_completion.d/scan4log4shell
      - src: ./completions/scan4log4shell.fish
        dst: /usr/share/fish/completions/scan4log4shell.fish
      - src: ./completions/scan4log4shell.zsh
        dst: /usr/local/share/zsh/site-functions/_scan4log4shell
    formats:
    - apk
    - deb
    - rpm